# Site settings
title:          Short Thoughts
description:    "A microblogging site of my own"
baseurl:        "/testblog"   # change this when I move the site 
# url:

# https://jekyllrb.com/docs/configuration/options/
timezone: America/Los_Angeles

# Author
author:
  name:         Nina Zumel
  url:          https://ninazumel.com
  email:        nzumel@mzlabs.com

footer:
  links:
    - label: "Micro.blog"
      icon: "fab fa-fw fa-microblog fa-lg" 
      url: "https://micro.blog/MultoGhost"
    - label: "Multo (Ghost)"  
      icon: "fab fa-fw fa-wordpress fa-lg" 
      url: "https://multoghost.wordpress.com/"



# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     /assets/css/_sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
#  - jekyll-seo-tag
#  - jekyll-last-modified-at

# Permalinks
# permalink:      /:title
permalink: /:categories/:year/:month/:day/:title:output_ext
paginate:       5

# Excludes
exclude:
  - README.md
  - LICENSE.md

# Disqus (Set to your disqus id)
# disqus:
